#**************************************************************************
#   Copyright (C) 2005 by Jeff Ferr                                       *
#   root@sat                                                              *
#                                                                         *
#   This program is free software; you can redistribute it and/or modify  *
#   it under the terms of the GNU General Public License as published by  *
#   the Free Software Foundation; either version 2 of the License, or     *
#   (at your option) any later version.                                   *
#                                                                         *
#   This program is distributed in the hope that it will be useful,       *
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
#   GNU General Public License for more details.                          *
#                                                                         *
#   You should have received a copy of the GNU General Public License     *
#   along with this program; if not, write to the                         *
#   Free Software Foundation, Inc.,                                       *
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
#**************************************************************************
GENERIC_OBJS = \
		 ../generic/genericprovider_bmp.o\
		 ../generic/genericprovider_gif.o\
		 ../generic/genericprovider_ico.o\
		 ../generic/genericprovider_jpg.o\
		 ../generic/genericprovider_pcx.o\
		 ../generic/genericprovider_png.o\
		 ../generic/genericprovider_ppm.o\
		 ../generic/genericprovider_tga.o\
		 ../generic/genericprovider_xbm.o\
		 ../generic/genericprovider_xpm.o\

CCFLAGS 	+= \
     -Ijgui/binds \
	   `pkg-config --cflags cairo` \

LDFLAGS		+= \
	   `pkg-config --libs cairo` \

REQUIRES	+= \
		 cairo \

# choose the graphic engine

ifeq ($(ENABLE_GRAPHICS),sdl2)
	CCFLAGS 	+= \
		 `pkg-config --cflags sdl2` \

	LDFLAGS		+= \
		 `pkg-config --libs sdl2` \
		 -ljpeg \

	DEFINES		+= \
		 -DSDL2_UI \

	REQUIRES	+= \
		 sdl2 \

	OBJS_gfx	+= \
		 $(GENERIC_OBJS)\
		 sdl2application.o\

	OBJS_jgui	= $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),sfml2)
	CCFLAGS 	+= \

	LDFLAGS		+= \
		 -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio \
     -ljpeg \

	DEFINES		+= \
		 -DSFML2_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 $(GENERIC_OBJS)\
		 sfml2application.o\

	OBJS_jgui	= $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),xlib)
	CCFLAGS 	+= \

	LDFLAGS		+= \
     `pkg-config --libs x11` \
     -ljpeg \

	DEFINES		+= \
		 -DXLIB_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 $(GENERIC_OBJS)\
		 xlibapplication.o\

	OBJS_jgui	= $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),xcb)
	CCFLAGS 	+= \

	LDFLAGS		+= \
     `pkg-config --libs xcb` \
     -ljpeg \

	DEFINES		+= \
		 -DXCB_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 $(GENERIC_OBJS)\
		 xcbapplication.o\

	OBJS_jgui	= $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),gtk3)
	CCFLAGS 	+= \
		 `pkg-config --cflags gtk+-3.0` \

	LDFLAGS		+= \
		 `pkg-config --libs gtk+-3.0` \
		 -ljpeg \

	DEFINES		+= \
		 -DGTK3_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 $(GENERIC_OBJS)\
		 gtk3application.o\

	OBJS_jgui	= $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),allegro5)
	CCFLAGS 	+= \
		 `pkg-config --cflags allegro-5 allegro_video-5 allegro_main-5` \

	LDFLAGS		+= \
		 `pkg-config --libs allegro-5 allegro_video-5 allegro_main-5` \
		 -ljpeg \

	DEFINES		+= \
		 -DALLEGRO5_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 $(GENERIC_OBJS)\
		 allegro5application.o\

	OBJS_jgui	= $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

