#**************************************************************************
#   Copyright (C) 2005 by Jeff Ferr                                       *
#   root@sat                                                              *
#                                                                         *
#   This program is free software; you can redistribute it and/or modify  *
#   it under the terms of the GNU General Public License as published by  *
#   the Free Software Foundation; either version 2 of the License, or     *
#   (at your option) any later version.                                   *
#                                                                         *
#   This program is distributed in the hope that it will be useful,       *
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
#   GNU General Public License for more details.                          *
#                                                                         *
#   You should have received a copy of the GNU General Public License     *
#   along with this program; if not, write to the                         *
#   Free Software Foundation, Inc.,                                       *
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
#**************************************************************************
CCFLAGS 	+= \
     -Ijgui \
	   `pkg-config --cflags cairo` \
	   `pkg-config --cflags libheif` \
	   `pkg-config --cflags libwebp` \
     `pkg-config --cflags librsvg-2.0` \

LDFLAGS		+= \
     `pkg-config --libs cairo` \
     `pkg-config --libs libheif` \
     `pkg-config --libs libwebp` \
     `pkg-config --libs librsvg-2.0` \
     -ljasper \
     -ltiffxx \
     -ljpeg \
     /usr/local/lib/libbpg.a \

REQUIRES	+= \
		 cairo \

OBJS_jgui	+= \
     providers/imageprovider_bmp.o \
		 providers/imageprovider_gif.o \
		 providers/imageprovider_ico.o \
		 providers/imageprovider_jpg.o \
		 providers/imageprovider_pcx.o \
		 providers/imageprovider_png.o \
		 providers/imageprovider_ppm.o \
		 providers/imageprovider_tga.o \
		 providers/imageprovider_xbm.o \
		 providers/imageprovider_xpm.o \
		 providers/imageprovider_heif.o \
		 providers/imageprovider_webp.o \
		 providers/imageprovider_jp2000.o \
		 providers/imageprovider_svg.o \
		 providers/imageprovider_tif.o \
		 providers/imageprovider_bpg.o \
		 providers/imageprovider_flif.o \

# choose the graphic engine

ifeq ($(ENABLE_GRAPHICS),sdl2)
	CCFLAGS 	+= \
		 `pkg-config --cflags sdl2` \

	LDFLAGS		+= \
		 `pkg-config --libs sdl2` \
		 -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DSDL2_UI \

	REQUIRES	+= \
		 sdl2 \

	OBJS_gfx	+= \
		 sdl2application.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),sfml2)
	CCFLAGS 	+= \

	LDFLAGS		+= \
		 -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio \
     -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DSFML2_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 sfml2application.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),xlib)
	CCFLAGS 	+= \

	LDFLAGS		+= \
     `pkg-config --libs x11` \
     -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DXLIB_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 xlibapplication.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),xcb)
	CCFLAGS 	+= \

	LDFLAGS		+= \
     `pkg-config --libs xcb` \
     -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DXCB_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 xcbapplication.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),gtk3)
	CCFLAGS 	+= \
		 `pkg-config --cflags gtk+-3.0` \

	LDFLAGS		+= \
		 `pkg-config --libs gtk+-3.0` \
		 -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DGTK3_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 gtk3application.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),allegro5)
	CCFLAGS 	+= \
		 `pkg-config --cflags allegro-5 allegro_video-5 allegro_main-5` \

	LDFLAGS		+= \
		 `pkg-config --libs allegro-5 allegro_video-5 allegro_main-5` \
		 -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DALLEGRO5_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 allegro5application.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),gl)
	CCFLAGS 	+= \
		 `pkg-config --cflags gl glu` \

	LDFLAGS		+= \
		 `pkg-config --libs gl glu` \
     -lglut \
		 -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DGL_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 glapplication.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),rpi)
	CCFLAGS 	+= \
		 -I/opt/vc/include -L/opt/vc/lib \

	LDFLAGS		+= \
     -lbcm_host \
     -lm \
     -lpng \
     -lpthread \
		 -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DRPI_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 rpiapplication.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),vdpau)
	CCFLAGS 	+= \

	LDFLAGS		+= \
     `pkg-config --libs x11` \
     `pkg-config --libs vdpau` \
     -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DVDPAU_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 vdpauapplication.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

ifeq ($(ENABLE_GRAPHICS),vnc)
	CCFLAGS 	+= \

	LDFLAGS		+= \
     `pkg-config --libs libvncserver` \
     -ljpeg \

	DEFINES		+= \
     -DJGUI_UI \
		 -DVNC_UI \

	REQUIRES	+= \

	OBJS_gfx	+= \
		 vncapplication.o\

  OBJS_jgui	+= \
     $(addprefix binds/$(ENABLE_GRAPHICS)/,$(OBJS_gfx))

endif

